// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmKNWB86pdDcxJlaEr0OgmyixPKoeverU',
    appId: '1:1028511013360:web:c8fe829ddfab5de7372535',
    messagingSenderId: '1028511013360',
    projectId: 'chat-79623',
    authDomain: 'chat-79623.firebaseapp.com',
    storageBucket: 'chat-79623.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKdbg4mDR-WIAVhTUjJAKfCQupZ7j7y0Y',
    appId: '1:1028511013360:android:8726fccf6bd14d3e372535',
    messagingSenderId: '1028511013360',
    projectId: 'chat-79623',
    storageBucket: 'chat-79623.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf5gVIT67RH5oZ3qxe9Fw1Vgq7k-bvycM',
    appId: '1:1028511013360:ios:d50ba47d992a2054372535',
    messagingSenderId: '1028511013360',
    projectId: 'chat-79623',
    storageBucket: 'chat-79623.firebasestorage.app',
    androidClientId: '1028511013360-0mrbs0pqv9jeonhnqhl99tf51i2qjvmu.apps.googleusercontent.com',
    iosClientId: '1028511013360-t8ua44kqa2b5idcspu0538ros2u3a9jg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf5gVIT67RH5oZ3qxe9Fw1Vgq7k-bvycM',
    appId: '1:1028511013360:ios:a76a9851e81f2008372535',
    messagingSenderId: '1028511013360',
    projectId: 'chat-79623',
    storageBucket: 'chat-79623.firebasestorage.app',
    androidClientId: '1028511013360-0mrbs0pqv9jeonhnqhl99tf51i2qjvmu.apps.googleusercontent.com',
    iosClientId: '1028511013360-t8ua44kqa2b5idcspu0538ros2u3a9jg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmKNWB86pdDcxJlaEr0OgmyixPKoeverU',
    appId: '1:1028511013360:web:a45b956c448e70e2372535',
    messagingSenderId: '1028511013360',
    projectId: 'chat-79623',
    authDomain: 'chat-79623.firebaseapp.com',
    storageBucket: 'chat-79623.firebasestorage.app',
  );
}